Repository SE-UUlm/votura, pull requests merged in 2025-09, with the labels that each got.

#326 #303 delete election UI
  apps/frontend/src/components/views/election/ElectionViewHeader.tsx
  apps/frontend/src/swr/elections/useDeleteElection.ts
  packages/e2e/tests/elections.test.ts
Labels: Frontend, Feature, EPIC: Elections, CAPI: Client API

#321 #267 [DB] Design vote persistence
  apps/docs/docs/devGuide/software_docs/cryptographicWorkflow.md
  apps/docs/static/drawio/voteBallotPaperSectionTable.drawio
  apps/docs/static/uml/dataModel.puml
  cspell.json
  package-lock.json
  packages/db/src/migrations/20250606_init.ts
  packages/db/src/nameEnums.ts
  packages/db/src/types/db.d.ts
  packages/e2e/tests/ballotPaper.test.ts
  packages/votura-validators/src/objects/filledBallotPaper.ts
  packages/votura-validators/src/schema/voting/castVotePathObject.ts
  packages/votura-validators/src/schema/voturaOpenApiSchema.ts
  packages/votura-validators/test/objects/filledBallotPaper.test.ts
Labels: DB: Database, Feature, Design

#322 #315 [BAPI] Refactor checks
  apps/backend/src/controllers/bodyChecks/userChecks.ts
  apps/backend/src/controllers/users.controllers.ts
  apps/backend/src/services/users.service.ts
Labels: Backend, Refactoring, BAPI: Backend API

#323 #318 [BAPI] Only allow creation of Voter tokens if election is ready
  apps/backend/src/middlewares/pathParamChecks/voterGroupChecks.ts
  apps/backend/src/routes/voterGroups.routes.ts
  apps/backend/src/services/voterGroups.service.ts
  apps/backend/test/elections/unfreezeElection.test.ts
  apps/backend/test/voterGroups/createVoterTokens.test.ts
Labels: Feature, EPIC: Voter Group, BAPI: Backend API

#340 #328 create new package for encrypting and decrypting own json models
  apps/backend/package.json
  apps/frontend/package.json
  package-lock.json
  packages/votura-ballot-box/.gitignore
  packages/votura-ballot-box/.prettierignore
  packages/votura-ballot-box/.prettierrc.mjs
  packages/votura-ballot-box/eslint.config.mjs
  packages/votura-ballot-box/package.json
  packages/votura-ballot-box/src/index.ts
  packages/votura-ballot-box/test/placeholder.test.ts
  packages/votura-ballot-box/tsconfig.build.json
  packages/votura-ballot-box/tsconfig.json
  packages/votura-ballot-box/vitest.config.mjs
Labels: Feature, EPIC: Voting

#343 #338 update dev setup guide
  apps/docs/docs/devGuide/envSetup.md
  apps/docs/docs/devGuide/projectDocs.md
  apps/docs/docs/devGuide/software_docs/backend/db/kysley.md
  apps/docs/docs/devGuide/software_docs/electionCreationProcess.md
  apps/docs/docs/devGuide/software_docs/frontend.md
  apps/docs/docs/devGuide/software_docs/overview.md
Labels: Documentation

#341 #329 move decryption from backend to new json encryptiondecryption package
  .github/workflows/testing.yml
  apps/backend/src/services/elections.service.ts
  packages/votura-ballot-box/src/decryption/ballotPaperSection.ts
  packages/votura-ballot-box/src/index.ts
  packages/votura-ballot-box/test/decryption/ballotPaperSection.test.ts
  packages/votura-ballot-box/test/placeholder.test.ts
  packages/votura-ballot-box/vitest.config.mjs
  packages/votura-crypto/src/index.ts
  packages/votura-crypto/test/index.test.ts
  packages/votura-crypto/test/utils.test.ts
  packages/votura-validators/src/index.ts
  packages/votura-validators/src/objects/filledBallotPaper.ts
  packages/votura-validators/test/objects/filledBallotPaper.test.ts
Labels: Feature, EPIC: Voting
